apiVersion: v1
kind: List
items:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: worker
  spec:
    strategy:
      type: Recreate
    replicas: 1
    selector:
      matchLabels:
        app: worker
    template:
      metadata:
        name: worker
        labels:
          app: worker
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: small
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    name: worker
        containers:
        - name: worker
          image: dhananjoy/crawlest
          ports:
          - containerPort: 3031
          resources:
            requests:
              memory: 2G
              cpu: 500m
          env:
          - name: REDIS_HOST
            value: redis
          - name: RETHINK_HOST
            value: rethink
          - name: RETHINK_TABLE_PAGE
            value: page_v1
          - name: RETHINK_TABLE_JSON
            value: json_v1
          - name: FETCH_CONCURRENCY
            value: "10"
          - name: HOSTNAME
            value: worker
- kind: Service
  apiVersion: v1
  metadata:
    name: worker
  spec:
    type: LoadBalancer
    ports:
    - name: worker
      port: 80
      targetPort: 3031
    selector:
      app: worker
